name: Workflow for Codecov Java
on: [push, pull_request]
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4.0.1
                with:
                    fetch-depth: 0

            -   name: Set up JDK 8
                uses: actions/setup-java@v4
                with:
                    distribution: 'temurin'
                    java-version: '8'

            -   name: Build with Maven and generate coverage report
                run: mvn clean verify

            -   name: Upload coverage reports to Codecov
                uses: codecov/codecov-action@v4.0.1
                env:
                    CODECOV_TOKEN: f12f30de-7bf2-4d9d-810d-40e78ac43fcf
                    slug: ZhaoJunLei0/codecov-test
